openshift/cert-manager-operator

bundle/manifests/cert-manager.clusterserviceversion.yaml
pkg/controller/deployment/generic_deployment_controller.go
pkg/controller/deployment/related_images.go
pkg/controller/deployment/related_images_test.go

https://issues.redhat.com/browse/AUTH-108
This PR provides the support for overriding the operand image by using the `RELATED_IMAGE_CERT_MANAGER` environmental variable.
This feature is required for:
- Flexibility in testing
- Supporting SHA Digest pinning and supporting the offline installation mode
- Respinning the images in case of CVE
For more information, please refer to the [OSBS documentation](https://osbs.readthedocs.io/en/latest/users.html#creating-the-relatedimages-section).

Use RELATED_IMAGE_CERT_MANAGER variable

---

README.md
bundle/manifests/cert-manager.clusterserviceversion.yaml
pkg/controller/deployment/default_cert_manager_controller.go
pkg/operator/starter.go

https://issues.redhat.com/browse/AUTH-105
This PR enables the Operator to always create the `certmanager/cluster` CR, so that other pieces of code could assume it's always there. This approach has stronger guarantees than defining the `certmanager/cluster` in the OLM bundle (someone can just delete it). The convention of having those objects comes down from library-go and core. Most of the controllers need it to write their status. 
This decision has a few consequences:
- We no longer need an example in the bundle. 
- We don't need to mention this requirement anywhere in the docs (but I'm doing it either way - to make users aware that there is something like this).

Always create certmanager/cluster CR

---

bundle/manifests/certificaterequests.cert-manager.io-crd.yaml
bundle/manifests/certificates.cert-manager.io-crd.yaml
bundle/manifests/challenges.acme.cert-manager.io-crd.yaml
bundle/manifests/clusterissuers.cert-manager.io-crd.yaml
bundle/manifests/issuers.cert-manager.io-crd.yaml
bundle/manifests/orders.acme.cert-manager.io-crd.yaml
jsonnet/main.jsonnet

This Pull Request fixes the following error:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": service "cert-manager-webhook" not found
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": service "cert-manager-webhook" not found
```

Fix namespace for conversion

---

bundle/manifests/cert-manager.clusterserviceversion.yaml
pkg/controller/deployment/related_images.go
pkg/controller/deployment/related_images_test.go

This Pull Request introduces the support for multiple image overrides. During the downstream productization, the images will be replaced with all-in-one image.
This is a counterpart for https://github.com/openshift/release/pull/26351

Support multiple image overrides

---

Makefile

This allows the default build-machinery calls to happen when user follows the README instructions to `make local-run`

Add non-existent target dependency to local-run

---

bundle/manifests/cert-manager.clusterserviceversion.yaml

Change CSV annotation `operators.openshift.io/valid-subscription` in bundle/manifests to remove erroneous 'OpenShift Kubernetes Engine'.
xref: http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/cert-manager-operator-bundle-container-v1.9.1-11/fd9b45f0-603f-477e-a04d-433c16bc68bc/operator-valid-subscriptions-bundle-image-output.txt

Fix valid-subscription annotation in manifests/csv

---

go.mod
pkg/controller/deployment/unsupported_config_overrides.go
pkg/controller/deployment/unsupported_config_overrides_test.go

Currently, using UnsupportedConfigOverrides does not take the union of the default args. This change allows the override to work such that it can merge expected default values with user provided overrides.

[CFE-698] Unsupported config overrides to use union of default args

---

Makefile
README.md
bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/samples/letsencrypt/cert-manager.io_v1_certificate.yaml
config/samples/letsencrypt/cert-manager.io_v1_issuer.yaml
config/samples/letsencrypt/extra/acme.cert-manager.io_v1_challenge.yaml
config/samples/letsencrypt/extra/acme.cert-manager.io_v1_order.yaml
config/samples/letsencrypt/extra/cert-manager.io_v1_certificaterequest.yaml
config/samples/selfsigned/cert-manager.io_v1_certificate.yaml
config/samples/selfsigned/cert-manager.io_v1_issuer.yaml

As a part of #83 we changed the operator namespace to use "cert-manager-operator" instead of "openshift-cert-manager-operator". In certain files such as README.md (upgrade section) as well as Makefile (local-run target) the value of the namespace reflects old value. This is intended at changing those values.
Additionally, the entries in alm-examples of the ClusterServiceVersion used to have `namespace: sample-namespace`, this PR would change it to `namespace: default` easing in applying the manifests.

Fix namespace in Makefile, change to default namespace in alm-examples

---

README.md
docs/OPERAND_METRICS.md

cert-manager supports metrics reporting using Prometheus. In this PR, I have documented the steps to enable the cert-manager (Operand) metrics and monitoring for the customers.
https://issues.redhat.com/browse/CFE-714

[CFE-715] Enable Cert-Manager Metrics

---

pkg/controller/deployment/unsupported_config_overrides.go
pkg/controller/deployment/unsupported_config_overrides_test.go

Un-ordered override causes deployment hash to be different causing repetitive deployment updates. This fixes the order only when container args are overridden.

Fix ordered args override

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Add seccompProfile RuntimeDefault to deployment which helps avoid pod security violation of operator pod(s).

CFE-754: Add seccompProfile RuntimeDefault to operator deployment

---

Makefile
bundle.Dockerfile
bundle/metadata/annotations.yaml

Add default channel as `stable-v1`
This is required for `index-image-build` make target, it fails without the `operators.operatorframework.io.bundle.channel.default.v1` label on Dockerfile &/ same annotation in metadata/annotations.yaml.

Add default channel as stable-v1

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
docs/proxy.md
go.mod
go.sum
pkg/cmd/operator/cmd.go
pkg/controller/deployment/cert_manager_cainjector_deployment.go
pkg/controller/deployment/cert_manager_controller_deployment.go
pkg/controller/deployment/cert_manager_controller_set.go
pkg/controller/deployment/cert_manager_webhook_deployment.go
pkg/controller/deployment/deployment_overrides.go
pkg/controller/deployment/generic_deployment_controller.go
pkg/operator/starter.go
vendor/github.com/operator-framework/operator-lib/LICENSE
vendor/github.com/operator-framework/operator-lib/proxy/doc.go
vendor/github.com/operator-framework/operator-lib/proxy/proxy.go
vendor/modules.txt

Description
---
This PR adds egress proxy injection support to the operator. Proxy environment variables will now be propagated to the operand from the operator deployment. This PR also provides an option to provide custom trusted CA certificates. 
- `pkg/controller/deployment/cert_manager_cainjector_deployment.go`, `pkg/controller/deployment/cert_manager_controller_set.go`, `pkg/controller/deployment/cert_manager_controller_deployment.go` and `pkg/controller/deployment/cert_manager_webhook_deployment.go` : Fix informers arg names and pass trusted CA configmap at runtime. 
- `pkg/controller/deployment/deployment_overrides.go` : Add 2 new deployment hooks to inject proxy env variables and inject trusted CA configmap as a volume. 
- …

CFE-755: Support cluster-wide egress proxy injection

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Change CSV annotation `operators.openshift.io/valid-subscription` to support 'OKE and up' subscriptions instead of current 'OCP and up' as required by PM.

Use OpenShift subscription as 'OKE and up'

---

docs/OPERAND_METRICS.md

Current syntax will make https://github.com/openshift/cert-manager-operator/tree/master/docs/OPERAND_METRICS.md preview not display the apiVersion line. If users copy the yaml snippets and apply, will hit error:
```
[xxia@2023-03-11 10:35:57 CST cert-manager-test]$ oc create -f servicemonitor-cert-manager.yaml -n cert-manager
error: resource mapping not found for name: "cert-manager" namespace: "cert-manager" from "servicemonitor-cert-manager.yaml": no matches for kind "ServiceMonitor" in version ""
ensure CRDs are installed first
```
/cc @swghosh @thejasn @ayesha54 @TrilokGeer

Fix incorrect syntax

---

Makefile

Add env vars needed in local-run make target which fixes an issue with operatorclient.EnsureFinalizer that was failing locally.
Helps avoid the following error (which was prevalent with `make local-run` during local debugging):
```
E0411 18:47:02.864606  215588 base_controller.go:272] cert-manager-controller-deployment reconciliation failed: CertManager.operator.openshift.io "cluster" is invalid: metadata.finalizers: Invalid value: "./cert-manager-operator.operator.openshift.io/cert-manager-controller-deployment": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain …
```

Add env vars for local-run make target

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
bundle/manifests/operator.openshift.io_certmanagers.yaml
config/manager/manager.yaml
pkg/controller/deployment/deployment_overrides.go
pkg/controller/deployment/related_images.go

Description
---
Adds a new ENV variable to read the ACME solver image at runtime. Related PR on midstream will update the image to reference Red Hat's image. 
Related Midstream PR: https://gitlab.cee.redhat.com/cpaas-midstream-cfe/openshift-cert-manager/-/merge_requests/96

OCPBUGS-10821: Update ACME solver image to read from env 

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Description
---
Add annotation to disable operand delete option on console. This acts as a check, to ensure deletion is done manually. 
cc: @xenolinux docs updated required for manual deletion

OCPBUGS-9960: Add disable operand delete annotation

---

pkg/controller/deployment/deployment_overrides_validation.go

Fixes a nil panic caused via deployment_overrides_validation.go due to incorrectly passing value of controllerConfig instead of webhookConfig/caInjectorConfig

OCPBUGS-14129: Nil panic fix in validateLabels

---

docs/proxy.md

/cc @swghosh @thejasn 
The display in https://github.com/openshift/cert-manager-operator/blob/master/docs/proxy.md does not hide ```bash, it displays as:
```bash
oc -n cert-manager-operator patch subscription cert-manager-operator ...
```
Also, the subscription name (if installed via web) is `openshift-cert-manager-operator` instead. https://docs.openshift.com/container-platform/4.12/security/cert_manager_operator/cert-manager-operator-proxy.html needs update to be `subscription openshift-cert-manager-operator` as well (didn't catch this when GA sorry), CC @bergerhoffer .

Fix proxy.md

---

Makefile
bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Description
---
This PR creates a new operator version v1.10.3 while retaining the operand version at v1.10.2. This z-stream bump is required in order to bump dependencies in operator/operand that are present during the build process on CPaaS. 
- Current Go Version in 1.10.2
- cert-manager-operator-container-v1.10.2-16 : openshift-golang-builder-container-v1.19.2-202210260124.el9.g6fef344
- jetstack-cert-manager-container-v1.10.2-15 : openshift-golang-builder-container-v1.19.2-202210260124.el9.g6fef344
- Need to bump to 1.19.9 golang builder for 1.10.3 (z-stream bump for bug fixes)
Corresponding CPaaS bump: https://gitlab.cee.redhat.com/cpaas-midstream-cfe/openshift-cert-manager/-/merge_requests/120

CM-119: Bump cert manager operator 1.10.3

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Description
---
Allow installing older versions of the operator that are available on the same channel. Skips allows users to install versions lower than the channel head.
After this fix users will be able to install older versions but there is a small caveat w.r.r `InstallPlanApproval`.
Users who are installing older versions will need to set `installPlanApproval: Manual` without which they can install the older version but OLM will automatically upgrade it to the latest supported version in that channel. Meaning in our case if they install `1.10.2` or `1.11.1` (both are in the `stable-v1`) channel, they will get upgraded to the `1.11.4` release.
Current state of bundles in the stable-v1 channel,
- cert-manager-1.10.2 has no skips (older releases)
- cert-manager-1.11.1 has no skips …

CM-132: Add skips to allow older installations

---

Dockerfile
images/ci/Dockerfile

Use ubi:9.2 base image for Dockerfile(s)

---

pkg/controller/deployment/deployment_overrides_validation.go
test/e2e/cert_manager_deployment_test.go

This PR adds the support for the flag `--enable-certificate-owner-ref`. This flag can be enabled by adding it to the `spec.controllerConfig.overrideArgs` field of the CertManager `cluster` object. When the flag is enabled the certificate resource is set as an owner of secret where the tls certificate is stored and the secret will be automatically removed when the certificate resource is deleted.

CM-98: Add --enable-certificate-owner-ref as supported cert-manager controller arg

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml

Update rbac proxy patch to remove stale node affinity config

OCPBUGS-19446: Remove nodeaffinity from rbac proxy patch

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

[CM-208](https://issues.redhat.com/browse/CM-208) / [CM-201](https://issues.redhat.com/browse/CM-201) CSV labels to support arm64, ppc64le and s390x architectures. 
```
operatorframework.io/arch.arm64: supported
operatorframework.io/arch.ppc64le: supported
operatorframework.io/arch.s390x: supported
```

CM-201,CM-208: add CSV labels for non-amd64 architectures

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml

add nodeaffinity for non-x86 archs
- arm64
- ppc64le
- s390x
https://issues.redhat.com/browse/CM-215

CM-215: add nodeaffinity for non-x86 archs

---

.ci-operator.yaml
Makefile
go.mod
images/ci/Dockerfile

- Bump builder to golang-1.20-openshift-4.14
- Update go.mod to go=1.20

[cert-manager-1.11] Bump golang to 1.20

---

README.md

Add a short note for specify target platforms for Docker and Podman when executing `make image-build`.
https://issues.redhat.com/browse/OCPBUGS-22954

OCPBUGS-22954: add note for non-x86 arch image building

---

test/e2e/overrides_test.go
test/e2e/utils_test.go

Mainly refer to override args logic.
* add util funcs `addOverrideResources` and `verifyDeploymentResources `
* add 1 valid and 1 invalid cases for each operand: controller, cainjector, webhook
It's the initial attempt to add new e2e test in dev's repo.
Test profile: [aos-4_14/ipi-on-aws/versioned-installer-ci](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/249313/)
<details>
<summary>Pass log</summary>
```
Overrides test
/Users/yuewu/Documents/workspace/fork/cert-manager-operator/test/e2e/overrides_test.go:16
When adding valid cert-manager controller override resources
/Users/yuewu/Documents/workspace/fork/cert-manager-operator/test/e2e/overrides_test.go:146
should add the resources to the cert-manager controller deployment …
```

CM-230: Add e2e test for operands override resources

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Added Infrastructure features for OpenShift catalog metadata as per [CFC best practices](https://docs.engineering.redhat.com/display/CFC/Best_Practices).
PS: OCPBUGS-8665 reference for addition of `token-auth-azure`. While `token-auth-aws` and `token-auth-gcp` was implemented previously in https://github.com/openshift/cert-manager-operator/pull/120 and `proxy-aware` in https://github.com/openshift/cert-manager-operator/pull/103.

CM-183: Add infrastructure feature annotations

---

.ci-operator.yaml
Dockerfile
Makefile
go.mod
go.sum
images/ci/Dockerfile

This is follow-up PR of #174. This PR bumps the go version to 1.21.
```sh
go mod edit -go=1.21
go mod tidy
go mod vendor
```

CM-295: Bump go version to go 1.21

---

.ci-operator.yaml
Dockerfile
Makefile
go.mod
go.sum
images/ci/Dockerfile

Pulls #175 to cert-manager-1.14 branch.

[cert-manager-1.14] CM-295: Bump go version to go 1.21

---

Makefile
bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
images/ci/Dockerfile
images/ci/operand.Dockerfile

- `strictfipsruntime` mode for Go build
- build operand on CI (instead of mirroring from jetstack upstream)
- enable `features.operators.openshift.io/fips-compliant` in CSV
Refer https://github.com/openshift/release/pull/51700 for rehearsed PoC.

CM-333: Go build(s) with strictfipsruntime

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml

kube-rbac-proxy:latest image from [RH catalog](https://catalog.redhat.com/software/containers/openshift4/ose-kube-rbac-proxy/5cdb2634dd19c778293b4d98?architecture=amd64&image=664e863c3ac7bfa8cd232e43&container-tabs=overview) still do not have the bumped `golang.org/x/net` with remediated CVE for http2.
Hence, disabling http2 on the kube-rbac-proxy.

CM-331: Disable kube-rbac-proxy http2

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Adding support for 'All Namespace' mode on install time.

OCPBUGS-23406: Enable AllNamespaces install mode

---

test/e2e/cert_manager_deployment_test.go
test/e2e/testdata/acme/deployment.yaml
test/e2e/utils_test.go

PR contain below changes:
- Moved securityContext properties in ACME deployment to container spec.
- Added debug logs on TestCertRenew.
- Changes variable names from snake case to camel case in TestCertRenew.
- Compare certificate's pre-fetched NotAfter value from status subresource against the dynamically fetched certificate in the poll block, which guess was causing the sporadic failures.

OCPBUGS-34698: Fix for TestCertRenew sporadic failures

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml

This avoids blocking upgrades in a limited connectivity/airgapped env where on prior images are pulled before an upgrade, which is per [the related enhancement guidance](https://github.com/openshift/enhancements/blob/master/enhancements/update/dont-require-registry-during-reboot-and-upgrade.md#dont-use-the-always-pull-policy).

OCPBUGS-24193: Use `imagePullPolicy: IfNotPresent` for operator deployment

---

test/e2e/certificates_test.go
test/e2e/testdata/acme/certificate_ibmcis.yaml
test/e2e/testdata/acme/clusterissuer_ibmcis.yaml

Issue: https://issues.redhat.com/browse/MULTIARCH-3780
updated https://github.com/openshift/cert-manager-operator/blob/master/test/e2e/certificates_test.go
Added new tests:
- dns-01 challenge using explicit credentials on ibm cloud CIS
Modified existing tests:
- dns-01 challenge using explicit credentials
- dns-01 challenge using ambient credentials

MULTIARCH-3780: Added Test Case Modification for IBMCloud and Power

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

As a result of the 1.14.1 z-stream, we need to update the OLM replaces and skipRange to factor in the v1.14.1 inclusion for the update graph.
This a follow-up over #205.

CM-409: Update replaces and skipRange to include 1.14.1

---

Makefile
go.mod
go.sum
test/e2e/certificates_test.go
vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
vendor/github.com/onsi/ginkgo/v2/CONTRIBUTING.md
vendor/github.com/onsi/ginkgo/v2/Makefile
vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/package_hash.go
vendor/github.com/onsi/ginkgo/v2/internal/suite.go
vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
vendor/github.com/onsi/ginkgo/v2/table_dsl.go
vendor/github.com/onsi/ginkgo/v2/types/config.go
vendor/github.com/onsi/ginkgo/v2/types/label_filter.go
vendor/github.com/onsi/ginkgo/v2/types/version.go
vendor/modules.txt

Main changes:
- Bump onsi/gingko/v2 to [v2.19](https://github.com/onsi/ginkgo/releases/tag/v2.19.0).
- To make use of the newly introduced [Label Sets](https://onsi.github.io/ginkgo/#label-sets) feature. Benefits:
- It is more expressive and human-readable than regexp combining `--focus` and `--skip`.
- It extends the current `--label-filter` to support filtering by key-value pairs, with the contains and not contains operations for the labels that have values. (more example usages can be found in the [doc](https://onsi.github.io/ginkgo/#label-sets))
- It gives more flexibility in filtering and sorting tests based on labels. As the test suite grows, we might apply more label types to identify Serial/Disruptive, Alpha/Beta, Conformance/MinVersion:xxx, etc.
- Add an env variable …

CM-261: utilize ginkgo label filter to differentiate cloud platforms

---

test/e2e/certificates_test.go

Configuring an ACME issuer by using explicit credentials for GCP CloudDNS
Similair to "[should obtain a valid LetsEncrypt certificate](https://github.com/openshift/cert-manager-operator/blob/207d9062d78f16b786998a7989d2487eee77bf21/test/e2e/certificates_test.go#L66)", but change to use CloudDNS DNS-01 solver
Pass log:
```
go test \
-timeout 1h \
-count 1 \
-v \
-p 1 \
-tags e2e \
-run "" \
./test/e2e \
-ginkgo.label-filter="Platform: isSubsetOf {GCP}"
------------------------------
ACME Certificate
/Users/yuewu/Documents/workspace/fork/ocp-cert-manager-operator/test/e2e/certificates_test.go:35
dns-01 challenge with Google CloudDNS [Platform:GCP]
/Users/yuewu/Documents/workspace/fork/ocp-cert-manager-operator/test/e2e/certificates_test.go:383
should obtain a valid LetsEncrypt certificate …
```

CM-318: Add case to use explicit credentials in ACME DNS-01 on GCP

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/samples/letsencrypt/cert-manager.io_v1_issuer.yaml

Remove angular brackets `< >` used in sample manifests which are escaped when bundle manifest is generated by operator-sdk. And the escape characters added is causing json unmarshling issue when validating the fbc image in konflux.
Check fbc build https://console.redhat.com/application-pipeline/workspaces/cert-manager-oape/applications/cert-manager-operator-fbc-1-15/pipelineruns/cert-manager-operator-fbc-1-15-on-pull-request-8t8cv/detail for validation error reported.

CM-376: Remove angular brackets in config manifests

---

test/e2e/cert_manager_deployment_test.go
test/e2e/certificates_test.go
test/library/utils.go

Main changes:
- Add a helper func `DumpEventsInNamespace()` for e2e tests to log namespaced events before each testing namespace is destroyed.  (inspired by [dumpEventsInNamespace](https://github.com/kubernetes/kubernetes/blob/d9b95ea94f41b942440adbdfdbe35fb78a2ed6f7/test/e2e/framework/debug/dump.go#L41)) It'd be invoked when e2e cases are failing (applicable to both go-testing and Ginkgo suite). Example logs:
```
2024/10/25 14:37:06 Dumping events in namespace e2e-acme-certs-nrz8v...
2024/10/25 14:37:07 At 2024-10-25 14:27:05 +0800 CST - event for CertificateRequest letsencrypt-cert-1: {cert-manager-certificaterequests-issuer-acme } WaitingForApproval: Not signing CertificateRequest until it is Approved
2024/10/25 14:37:07 At 2024-10-25 14:27:05 +0800 CST - event for CertificateRequest …
```

 NO-JIRA: add helper func to dump events while e2e cases are failing

---

Makefile
hack/go-fips.sh

checks for availability of GOEXPERIMENT strictfipsruntime before `go build`, 
warns the user and proceeds, 
without this change operator cannot be built for local testing/debugging.

fix: allow `make build` to run w/o strictfipsruntime (locally)

---

test/e2e/cert_manager_deployment_test.go
test/e2e/certificates_test.go
test/e2e/istio_csr_test.go
test/e2e/testdata/istio/istio_ca_issuer.yaml
test/e2e/testdata/istio/istio_csr.yaml
test/e2e/utils_test.go
test/library/utils.go

The PR adds the e2e test scenarios for the new istio-csr controller.
- Apply's the new IstioCSR resource in the istio-system namespace
- Create a new job - grpcurl-job which calls the endpoint of the istio-csr
- Waits for the response and validates the certificate and the root chain

CM-423: Adds e2e test for istio-csr controller with grpc CreateCertificate call

---

test/e2e/certificates_test.go
test/e2e/config_template.go
test/e2e/testdata/acme/certificate_gcp.yaml
test/e2e/testdata/acme/certificate_ibmcis.yaml
test/e2e/testdata/acme/clusterissuer_gcp.yaml
test/e2e/testdata/acme/clusterissuer_ibmcis.yaml

For extensible replacement of field values in the yaml(s) used within e2e `testdata/` through config structs, 
the go `text/template` allows for better replacement support; aids readability as well.

Refactor `test/e2e/testdata` to use go template based replacements

---

main.go

Go 1.20 automatically seeds the top-level generator and deprecated `rand.Seed`.  Read more [here](https://go.dev/blog/randv2#fix.v1).

Implements rand deprecation by removing seed initializer

---

test/e2e/config_template.go
test/e2e/istio_csr_test.go
test/e2e/testdata/istio/grpcurl_job.yaml
test/e2e/utils_test.go

Refactor the e2e test case for istio-csr controller
- parse the IstioCSR object using an unstructured converter, read resource status fields
- move the grpcurl Job into a `testdata` file, apply with dynamic_resource_loader and config template values

CM-423: Improves e2e test for istio-csr controller to read from resource status

---

test/e2e/cert_manager_deployment_test.go
test/e2e/certificates_test.go
test/e2e/config_template.go
test/e2e/istio_csr_test.go
test/e2e/testdata/acme/certificate_gcp.yaml
test/e2e/testdata/acme/certificate_ibmcis.yaml
test/e2e/testdata/acme/clusterissuer_gcp.yaml
test/e2e/testdata/acme/clusterissuer_ibmcis.yaml
test/e2e/testdata/istio/grpcurl_job.yaml
test/e2e/testdata/istio/istio_ca_issuer.yaml
test/e2e/testdata/istio/istio_csr.yaml
test/e2e/utils_test.go
test/library/utils.go

Manual cherry-pick of #212, #226, #247, #248 into cert-manager-1.15 branch.

[cert-manager-1.15] CM-423: Adds e2e test for istio-csr controller with grpc CreateCertificate call

---

api/operator/v1alpha1/features.go
bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml
pkg/cmd/operator/cmd.go
pkg/features/features.go
pkg/features/features_test.go
pkg/operator/starter.go
test/e2e/certificates_test.go
test/e2e/istio_csr_test.go
test/e2e/utils_test.go

Adds `--unsupported-addon-features` arg to the operator binary, which when contains `"IstioCSR=true"` turns on the controller-runtime based istio-csr controller (which was added in #220).
From a user perspective, if they wish to use unsupported addons they can patch the OLM Subscription object with the `UNSUPPORTED_ADDON_FEATURES` env variable for it to get enabled at operator startup.

CM-424: Allow experimental features to be turned on from `--unsupported-addon-features`

---

pkg/controller/istiocsr/deployments.go
pkg/controller/istiocsr/test_utils.go
pkg/controller/istiocsr/utils.go
test/e2e/certificates_test.go
test/library/utils.go

No need to reference `.ObjectMeta` when trying to access certain variables.
Broken out from #259 for easier reviewing.

Remove unnecessary .ObjectMeta

---

pkg/controller/deployment/deployment_overrides.go

Broken out from #259 into a smaller PR.
Similar to: https://github.com/openshift-kni/cnf-features-deploy/pull/2345

Use `k8s.io/utils/ptr` instead of deprecated `k8s.io/utils/pointer`

---

test/e2e/overrides_test.go
test/e2e/utils_test.go

Improves the `verifyOperatorStatusCondition` function to not allow bypassing `status.Conditions` when empty or has the required condition type(s) missing.
In #263, we managed to get the e2e pass with a faulty status update client that always kept the conditions array empty in the certmanager.operator/cluster resource.
- eg. [job that Succeeded](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cert-manager-operator/263/pull-ci-openshift-cert-manager-operator-master-e2e-operator/1912101154230112256) and it's corresponding [operator log with panics](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cert-manager-operator/263/pull-ci-openshift-cert-manager-operator-master-e2e-operator/1912101154230112256/artifa …

Avoid e2e to pass with faulty status

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

As part of https://issues.redhat.com/browse/CM-429
Some CI results can be referenced: https://github.com/openshift/release/pull/63331#issuecomment-2834027775
--
Other change:
Remove v4.14+ deprecated `operators.openshift.io/infrastructure-features` to avoid confusion and inconsistency. Ref: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/operators/developing-operators#osdk-csv-manual-annotations-deprecated_osdk-generating-csvs

CM-499: Enable disconnected support via annotation in operator CSV

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml

Updates the ClusterServiceVersion to include maxOpenShiftVersion (as 4.19, which is the highest supported version target for operator 1.16.0)

Update min Kubernetes version in CSV

---

docs/operand_metrics.md

- Updated steps based on upstream v1.16 introduced [extended metrics](https://cert-manager.io/docs/releases/release-notes/release-notes-1.16/#extended-metrics) for cainjector and webhook.
- Removed outdated or redundant steps, validated with cert-manager operator v1.16 staging build on OpenShift 4.18

CM-574: Enhance operand metrics doc based on latest builds

---

test/e2e/certificates_test.go
test/e2e/condition_matcher_test.go
test/e2e/condition_matcher_unit_test.go
test/e2e/istio_csr_test.go
test/e2e/overrides_test.go
test/e2e/suite_test.go
test/e2e/utils_test.go

Protect against arbitrary `*Degraded` conditions as true and deliberately fail the e2e if we encounter any unexpected Degraded in Status.Conditions.
Currently, if `cert-manager-*-deploymentDegraded` is True the e2e would fail but in the event of a Condition `{Type: "cert-manager-controller-static-resources-Degraded", status: "True"}` it does not error out which caused us to overlook such errors as observed in https://issues.redhat.com/browse/OCPBUGS-56758.
/cc @lunarwhite @siddhibhor-56

CM-590: deliberately fail the e2e on encountering an unexpected Degraded condition

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/rbac/role.yaml
pkg/controller/deployment/certmanager_controller.go

To mitigate the static-resource controller degrade issue caused by lack of permission: 
```
'RoleCreateFailed' Failed to create Role.rbac.authorization.k8s.io/cert-manager-tokenrequest -n cert-manager: roles.rbac.authorization.k8s.io "cert-manager-tokenrequest" is forbidden: user "system:serviceaccount:cert-manager-operator:cert-manager-operator-controller-manager" (groups=["system:serviceaccounts" "system:serviceaccounts:cert-manager-operator" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["serviceaccounts/token"], ResourceNames:["cert-manager"], Verbs:["create"]}
```
Adds the `serviceaccount/token` create permission to the RBAC annotations of [certmanager_controller.go](https://github.com/openshift/cert-manager-operator/bl …

OCPBUGS-56758: Add tokenrequest RBAC for operator controller manager

---

pkg/controller/deployment/cert_manager_cainjector_deployment.go
pkg/controller/deployment/cert_manager_controller_deployment.go
pkg/controller/deployment/cert_manager_controller_set.go
pkg/controller/deployment/cert_manager_webhook_deployment.go
pkg/controller/deployment/generic_deployment_controller.go
pkg/operator/optionalinformer/optional_informer.go
pkg/operator/optionalinformer/optional_informer_test.go
pkg/operator/starter.go

An optional informer that discovers a CRD before enacting,
applicable/useful for wrapping around configv1.Infrastructure which is not present when using a non-OpenShift cluster variant (eg. MicroShift).
Checklist:
-  [x] [Integration with Route(s) tested](https://github.com/openshift/cert-manager-operator/pull/278#issuecomment-2976727063)

CM-561: Turn o/api `configv1.Infrastructure` into an optional dependency

---

pkg/controller/deployment/deployment_overrides_validation.go

There is no supported overrideArgs to provide resources / limits for the solver pod. With this PR, those are to become accepted args.

RFE-7060,CM-588: Add `--acme-http01-solver-*` flags as supported cert-manager controller args

---

Makefile
bindata/istio-csr/cert-manager-istio-csr-clusterrole.yaml
bindata/istio-csr/cert-manager-istio-csr-clusterrolebinding.yaml
bindata/istio-csr/cert-manager-istio-csr-deployment.yaml
bindata/istio-csr/cert-manager-istio-csr-leases-role.yaml
bindata/istio-csr/cert-manager-istio-csr-leases-rolebinding.yaml
bindata/istio-csr/cert-manager-istio-csr-role.yaml
bindata/istio-csr/cert-manager-istio-csr-rolebinding.yaml
bindata/istio-csr/cert-manager-istio-csr-service.yaml
bindata/istio-csr/cert-manager-istio-csr-serviceaccount.yaml
bindata/istio-csr/istiod-certificate.yaml
bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml
pkg/operator/assets/bindata.go

Rebase istio-csr with upstream v0.14.2
- Update bindata manifests with istio-csr 0.14.2 
- update Makefile `ISTIO_CSR_VERSION`=v0.14.2
- make update
- make update-manifests update-bindata
- Manual replacement in `config/manager/manager.yaml`

CM-675: Rebase istio-csr with upstream v0.14.2

---

bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Supersede https://github.com/openshift/cert-manager-operator/pull/294
All cert-manager operands containers are applied with "readOnlyRootFilesystem: true" in their securityContext (aligned with upstream natively):
- cert-manager-controller https://github.com/openshift/cert-manager-operator/blob/bb69f735ac8611d97b02d012d6f99f0184a567a4/bindata/cert-manager-deployment/controller/cert-manager-deployment.yaml#L71
- cainjector https://github.com/openshift/cert-manager-operator/blob/bb69f735ac8611d97b02d012d6f99f0184a567a4/bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-deployment.yaml#L55
- webhook https://github.com/openshift/cert-manager-operator/blob/bb69f735ac8611d97b02d012d6f99f0184a567a4/bindata/cert-manager-deployment/webhook/cert-manager-webhook-deployment.yaml#L84
- …

CM-674: Enable ReadOnly Root Filesystem for operator controller

---

api/operator/v1alpha1/istiocsr_types.go
bundle/manifests/operator.openshift.io_istiocsrs.yaml
config/crd/bases/operator.openshift.io_istiocsrs.yaml
pkg/controller/istiocsr/deployments.go
pkg/controller/istiocsr/deployments_test.go
pkg/operator/applyconfigurations/operator/v1alpha1/serverconfig.go
test/e2e/config_template.go
test/e2e/istio_csr_test.go
test/e2e/suite_test.go
test/e2e/testdata/istio/grpcurl_job_with_cluster_id.yaml
test/e2e/testdata/istio/istio_csr_custom_cluster_id.yaml
test/e2e/utils_test.go

This PR extends the `istiocsr.operator.openshift.io` API to allow configuration of the Istio Cluster ID.
The istio-csr component validates incoming `CreateCertificate` gRPC requests from Istio by checking the `clusterid` in the request metadata. This change introduces a `clusterID` field in the IstioCSR spec, allowing users to specify the expected clusterID.
If the `clusterID` is not specified, it defaults to `"Kubernetes"`. This value is then passed as the `--cluster-id` command-line argument to the istio-csr deployment.

CM-680: [istio-csr] Enable multi-cluster support with clusterID

---

api/operator/v1alpha1/certmanager_types.go
bundle/manifests/operator.openshift.io_certmanagers.yaml
config/crd/bases/operator.openshift.io_certmanagers.yaml
pkg/controller/deployment/deployment_helper_test.go
test/e2e/overrides_test.go
test/e2e/utils_test.go

In https://github.com/openshift/cert-manager-operator/pull/237 we add the option to override the number of replicas for each cert-manager operand (controller, webhook, and cainjector) independently. This enables users to configure high availability setups and scale operands based on their specific operational requirements. This is a followup PR to enhance the tests coverage.
To keep goal focused, this PR doesn't handle `PodDisruptionBudget` or `PriorityClassName` which are also relevant to HA deployment setup. It would require dedicated design review if there is an RFE in future.
**NB: The credit should go to @appiepollo14 for implementing the initial PR** https://github.com/openshift/cert-manager-operator/pull/237

CM-718: Enhance tests for overriding replicas of HA deployment

---

bindata/istio-csr/cert-manager-istio-csr-metrics-service.yaml
hack/update-istio-csr-manifests.sh
pkg/controller/istiocsr/certificates.go
pkg/controller/istiocsr/client.go
pkg/controller/istiocsr/constants.go
pkg/controller/istiocsr/deployments.go
pkg/controller/istiocsr/rbacs.go
pkg/controller/istiocsr/serviceaccounts.go
pkg/controller/istiocsr/services.go
pkg/controller/istiocsr/utils.go
pkg/operator/assets/bindata.go

The PR has the following changes
- Adds metrics service static manifest.
- Creates the metrics service along with the core service.
- Updates the manifest fetch script to retain the metrics service manifest.
- Replaces `types.NamespacedName` with `client.ObjectKeyFromObject`

CM-639: Adds metrics service creation for istio-csr
