openshift/cert-manager-operator

- images/ci/Dockerfile
Required for https://github.com/openshift/release/pull/19608
> Remove non-existing manifests

- pkg/operator/assets/bindata.go
Required for https://github.com/openshift/release/pull/19608
> Fix make verify

- hack/update-clientgen.sh
Required to make https://github.com/openshift/release/pull/19608 pass﻿
> Make verification pass when using Image Builder

- bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-deployment.yaml
- bindata/cert-manager-deployment/controller/cert-manager-deployment.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-deployment.yaml
- jsonnet/main.jsonnet
- pkg/operator/assets/bindata.go
This Pull Request changes the directory of all binaries to `/usr/bin`.
> Align manifests with the container image

- pkg/controller/deployment/generic_deployment_controller.go
https://issues.redhat.com/browse/AUTH-118﻿
> Fix mechanism for replacing images

- Makefile
- bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-deployment.yaml
- bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-leaderelection-rb.yaml
- bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-sa.yaml
- bindata/cert-manager-deployment/cert-manager-namespace.yaml
- bindata/cert-manager-deployment/controller/cert-manager-deployment.yaml
- bindata/cert-manager-deployment/controller/cert-manager-leaderelection-rb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-sa.yaml
- bindata/cert-manager-deployment/controller/cert-manager-svc.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-deployment.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-dynamic-serving-rb.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-dynamic-serving-role.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-sa.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-svc.yaml
- jsonnet/main.jsonnet
- pkg/operator/assets/bindata.go
https://issues.redhat.com/browse/AUTH-137
This Pull Request moves all operands from `cert-manager` into `openshift-cert-manager` namespace.
> Auth 137 move operator to the openshift prefixed namespace

- bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-deployment.yaml
- bindata/cert-manager-deployment/controller/cert-manager-deployment.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-deployment.yaml
- jsonnet/main.jsonnet
- pkg/operator/assets/bindata.go
This Pull Request unifies binaries location with the upstream making the whole setup easier for manual testing.
> Unify binaries location with the upstream

- Makefile
This Pull Requests fixes path to CRDs in Makefile.
> Fix path to CRDs

- bundle/bundle.Dockerfile
- bundle/manifests/cert-manager.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- pkg/controller/deployment/cert_manager_cainjector_deployment.go
- pkg/controller/deployment/cert_manager_controller_deployment.go
- pkg/controller/deployment/cert_manager_controller_set.go
- pkg/controller/deployment/cert_manager_webhook_deployment.go
- pkg/controller/deployment/common.go
- pkg/controller/deployment/generic_deployment_controller.go
- pkg/operator/starter.go
This Pull Request introduces the following changes in the bundle:
- Add permissions to leases
- Use tech-preview instead of dev-preview
- Use the operand version
> Bundle updates

- bundle/manifests/cert-manager.clusterserviceversion.yaml
This Pull Request adds missing permissions for reporting and reading HA configuration in the cluster.
> Add reporting permissions

- Makefile
- bindata/cert-manager-deployment/cainjector/cert-manager-cainjector-crb.yaml
- bindata/cert-manager-deployment/cert-manager/cert-manager-controller-approve-cert-manager-io-crb.yaml
- bindata/cert-manager-deployment/cert-manager/cert-manager-controller-certificatesigningrequests-crb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-controller-certificates-crb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-controller-challenges-crb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-controller-clusterissuers-crb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-controller-ingress-shim-crb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-controller-issuers-crb.yaml
- bindata/cert-manager-deployment/controller/cert-manager-controller-orders-crb.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-mutatingwebhookconfiguration.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-subjectaccessreviews-crb.yaml
- bindata/cert-manager-deployment/webhook/cert-manager-webhook-validatingwebhookconfiguration.yaml
- jsonnet/main.jsonnet
- pkg/operator/assets/bindata.go
This Pull Request introduces the following updates:
- Use proper namespace for webhooks
- Use proper namespace for ClusterRoleBindings
> Use proper namespaces

- bindata/cert-manager-deployment/webhook/cert-manager-webhook-deployment.yaml
- jsonnet/main.jsonnet
- pkg/operator/assets/bindata.go
This Pull Request fixes the validation for serving cert name.
> Fix webhook serving cert

- Makefile
- README.md
- test/e2e/cert_manager_deployment_test.go
- test/e2e/testdata/self_signed/certificate.yaml
- test/e2e/testdata/self_signed/cluster_issuer.yaml
- test/e2e/testdata/self_signed/issuer.yaml
- test/e2e/testdata/self_signed/namespace.yaml
- test/library/dynamic_resources.go
- test/library/kube_client.go
- vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/meta.go
- vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
- vendor/modules.txt
This Pull Request introduces e2e tests for self-signed certs.
> end to end tests

- bundle/manifests/cert-manager.clusterserviceversion.yaml
https://issues.redhat.com/browse/CM-13
> CM-13 Added CR examples

- bundle/manifests/cert-manager.clusterserviceversion.yaml
https://issues.redhat.com/browse/CM-19
> CM-19 Added subscription

- bundle/manifests/cert-manager.clusterserviceversion.yaml
https://github.com/openshift/release/pull/27336 is required to get this green.
> Update image coordinates

- test/OWNERS.md
Added @xingxingxia @y4sht as reviewers and approvers for e2e tests
> Added owners for e2e tests

- bundle/manifests/cert-manager.clusterserviceversion.yaml
https://issues.redhat.com/browse/CM-21
https://issues.redhat.com/browse/CM-22
Took the Compliance Operator as an example: https://github.com/openshift/compliance-operator/blob/master/deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
> CM-21 CM-22 Bundle updates

- Makefile
- hack/verify-bundle.sh
> Add verify-bundle step to CI

- pkg/controller/deployment/credentials_request.go
Adds "AWS_SDK_LOAD_CONFIG" = "1" env var to cert-manager deployment when cloud credentials secrets in injected in case of AWS.
> OCPBUGS-14414: Add AWS_SDK_LOAD_CONFIG env var for aws sdk auth

- docs/cloud_credentials.md
- docs/operand_metrics.md
> Few doc changes

- test/e2e/certificates_test.go
- test/e2e/testdata/acme/certificate_gcp.yaml
- test/e2e/testdata/acme/clusterissuer_gcp.yaml
- test/e2e/testdata/credentials/credentialsrequest_gcp.yaml
- test/e2e/utils_test.go
- test/library/dynamic_resources.go
> CM-220: automate test case OCP-65035 on gcp

- test/e2e/certificates_test.go
Configuring an ACME Issuer by using ambient credentials on AWS
- Add `--issuer-ambient-credentials` argument in ACME Certificate's `BeforeAll()`
- Similair to "[should obtain a valid LetsEncrypt certificate in AWS mint/passthrough cluster](https://github.com/openshift/cert-manager-operator/blob/207d9062d78f16b786998a7989d2487eee77bf21/test/e2e/certificates_test.go#L177)", but change to use `Issuer`
> CM-257: Add case to use Issuer with "--issuer-ambient-credentials" on AWS

- .snyk
- bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
- config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Changes are required for building images using konflux to comply with enterprise policy contract.
> [cert-manager-1.15] CM-359 : Update operator CSV as required for the konflux

- .snyk
- bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
- config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Changes are required for building images using konflux to comply with enterprise policy contract.
> [cert-manager-1.14] CM-359 : Update operator CSV as required for the konflux

- OWNERS
Updates the reviewers and approvers list based on recent contributors and in-active members.
> Updates the reviewers and approvers

- bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
- config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
As title, fix minor nits found while trying to build v1.16.0 operator locally.
> Fix upstream version in CSV description
